[project]
name = "mistral-interview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "ipykernel>=7.2.0",
    "mistral-common>=1.9.1",
    "mistralai>=1.12.4",
    "numpy>=2.4.2",
    "openai>=2.26.0",
    "pydantic-settings>=2.13.1",
    "pypdf>=6.8.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.2",
    "requests>=2.32.5",
]
